name: Java CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build application
        run: |
          chmod +x mvnw
          ./mvnw clean package -DskipTests

      - name: Run Semgrep
        run: |
          python3 -m pip install semgrep

          semgrep scan \
            --config auto \
            --json \
            --output semgrep-report.json

          python3 semgrep_to_html.py

          echo "Semgrep scan completed."
          echo "Semgrep HTML and JSON reports generated."

      - name: Upload Semgrep reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-reports
          path: |
            semgrep-report.json
            semgrep-report.html

      - name: Download OWASP Dependency-Check
        run: |
          VERSION=$(curl -s https://dependency-check.github.io/DependencyCheck/current.txt)

          echo "Installing Dependency-Check version: $VERSION"

          curl -Ls \
            "https://github.com/dependency-check/DependencyCheck/releases/download/v${VERSION}/dependency-check-${VERSION}-release.zip" \
            -o dependency-check.zip

          unzip -q dependency-check.zip

      - name: Run OWASP Dependency-Check
        run: |
          mkdir -p dependency-check-report

          ./dependency-check/bin/dependency-check.sh \
            --project "Java Application" \
            --scan . \
            --format HTML \
            --format JSON \
            --out dependency-check-report \
            --enableRetired

      - name: Upload Dependency-Check reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-reports
          path: dependency-check-report/
